/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentes.principal;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author tritiummonoid
 */
public class PrincipalVista extends javax.swing.JFrame
        implements IPrincipalVista {

    private final PrincipalPresentador presentador;

    /**
     * Creates new form PrincipalVista
     * @param presentador
     */
    public PrincipalVista(PrincipalPresentador presentador) {
        initComponents();
        this.presentador = presentador;
        presentador.setVista(this);
        
        DefaultTreeCellRenderer renderer;
        renderer = (DefaultTreeCellRenderer) treeBasesDeDatos.getCellRenderer();
        Icon closedIcon = new ImageIcon("src/resources/db-icon.png");
        Icon openIcon = new ImageIcon("src/resources/db-icon.png");
        Icon leafIcon = new ImageIcon("src/resources/table-icon.png");
        renderer.setClosedIcon(closedIcon);
        renderer.setOpenIcon(openIcon);
        renderer.setLeafIcon(leafIcon);
        
        treeBasesDeDatos.getSelectionModel()
                .setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollBasesDeDatos = new javax.swing.JScrollPane();
        treeBasesDeDatos = new javax.swing.JTree();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();
        lblTabla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("dml4life");
        setLocation(new java.awt.Point(400, 250));

        treeBasesDeDatos.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                mostrar(evt);
            }
        });
        scrollBasesDeDatos.setViewportView(treeBasesDeDatos);

        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConsulta.setName("tblConsulta"); // NOI18N
        jScrollPane1.setViewportView(tblConsulta);

        lblTabla.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTabla.setText("Tabla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollBasesDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTabla)
                        .addGap(0, 455, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollBasesDeDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTabla)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrar(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_mostrar
        TreeNode nodo;
        nodo = (TreeNode) treeBasesDeDatos.getLastSelectedPathComponent();
        if (nodo != null && nodo.isLeaf()) {
            TreeNode padre = nodo.getParent();
            presentador.seleccionarTabla(padre.toString(), nodo.toString());
        }
    }//GEN-LAST:event_mostrar

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTabla;
    private javax.swing.JScrollPane scrollBasesDeDatos;
    private javax.swing.JTable tblConsulta;
    private javax.swing.JTree treeBasesDeDatos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cambioBasesDeDatos(TreeModel modelo) {
        treeBasesDeDatos.setModel(modelo);
    }

    @Override
    public void consultaInvalida() {
        JOptionPane.showMessageDialog(null, "Consulta inválida.");
    }

    @Override
    public void conexionFallida() {
        JOptionPane.showMessageDialog(null, "Conexión fallida.");
    }

    @Override
    public void cambioTabla(String nombre, TableModel tabla) {
        lblTabla.setText(nombre);
        tblConsulta.setModel(tabla);
    }

}
